service: supercharge-gcp-functions

provider:
  name: google
  runtime: nodejs8
  region: europe-west1
  project: supercharge-gcp-testing
  credentials: ./supercharge-gcp-key.json

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - test/**

functions:
  app:
    handler: http
    memorySize: 256 # default is 1024 MB
    events:
      - http: path

plugins:
  - serverless-google-cloudfunctions
  - serverless-offline
