service: supercharge-gcp-function-testing

provider:
  name: google
  runtime: nodejs8
  region: europe-west1
  project: supercharge-gcp-testing
  credentials: ./keyfile.json

functions:
  app:
    handler: httpHandler
    memorySize: 256 # default is 1024 MB
    events:
      - http: path

plugins:
  - serverless-google-cloudfunctions
  - serverless-offline

# package:
#   exclude:
#     - node_modules/**
#     - .eslintrc.json
#     - .gitignore
#     - .git/**
#     - test/**
#     - ava.config.js
#     - .env.example
